# Rubocop,  we're buddies and all,  but we're going to have to disagree on the following -

SingleSpaceBeforeFirstArg:
  Enabled: false

UnusedBlockArgument:
  Enabled: false

WordArray:
  MinSize: 5
